'use client'
import { useEffect } from "react";
import { useRouter } from 'next/navigation';
import { usePathname } from 'next/navigation';
import { isLoginUser } from "./utils/user";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Estimate app",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const isPrivateRoute = pathname?.startsWith('/private');


 const router = useRouter()
    
      
    useEffect(() => {
      const fetchUser = async () => {
      const isLogin = await isLoginUser();
        if (isLogin) {
          if (!isPrivateRoute) {
             await router.push('/private');
          }
        } 
     
    };
        fetchUser();
    
      }, []);

  return (
    <html lang="uk">
      <body>  
        {children}
      </body>
    </html>
  );
}
